version: '3'

services:
  pgsql:
    image: postgres:alpine
    container_name: grpc-pgsql
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    container_name: grpc-adminer
    restart: unless-stopped
    ports:
      - 8080:8080


volumes:
  pg-data:
